### ISSUE TITLE
App crashing after reload

### ISSUE THREAD

**Issue by Spharian** [pusher/pusher-websocket-react-native#43]
When reloading the app with CMD + D, this is logged to the console: `Invalidating RCTSampleTurboModule...`

Then, if I receive an event, it's crashing with the following error:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: onEvent with body: {
channelName = shows;
data = "[]";
eventName = "App\\Events\\RefreshShows";
userId = "<null>";
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter.'
*** First throw call stack:
(
0   CoreFoundation                      0x00000001803f3d70 __exceptionPreprocess + 236
1   libobjc.A.dylib                     0x000000018019814c objc_exception_throw + 56
2   Foundation                          0x000000018075b6c0 -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
3   projectname                               0x0000000100978000 -[RCTEventEmitter sendEventWithName:body:] + 400
4   projectname                               0x0000000100ca81fc $s29pusher_websocket_react_native26PusherWebsocketReactNativeC8callback4nam<…>
```

Anyone encountered this issue?

Expo: 46.0.16
React Native: 0.69.6
pusher-websocket-react-native: 1.1.0

**Comment by proggen-com** [comment]
Thanks, I'm investigating this issue, there seem to be many plugins having this issue googling the error.

**Comment by junix13** [comment]
Hi, I am experiencing the same issue with @Spharian .

So the issue occur, after reloading the app. Either pressing R or cmd + D and then reload. And after that, I tried sending an event and it gives me an error the same with Spharian.

`Thread 1: "Error when sending event: onEvent with body: {\n    channelName = \"my-channel\";\n    data = \"Test 3 after reload\";\n    eventName = Feedback;\n    userId = \"<null>\";\n}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter."`

**Comment by proggen-com** [comment]
Is this still an issue with 1.1.1 ?

**Comment by Braden1996** [comment]
> Is this still an issue with 1.1.1 ?

I am having this issue now on version 1.1.1 :(

**Comment by proggen-com** [comment]
Could it be some kind of race condition? If you connect to pusher a bit later does the error still occur?

**Comment by harrymash2006** [comment]
I am also getting the same issue

**Comment by junix13** [comment]
> 

Issue still occur at version 1.1.1 :(

**Comment by abelcha** [comment]
Made a PR with the fix:
https://github.com/pusher/pusher-websocket-react-native/pull/55
enjoy!

**Comment by barbarossusuz** [comment]
Any progress on this?

**Comment by Eigilak** [comment]
Experiencing the same error :(

**Comment by maxgod1** [comment]
I am using expo and redux to dispatch incoming messages. Logging the event works but when I try to dispatch I get this error.
`RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter.`

**Comment by Braden1996** [comment]
Is there any update to this? Seems a lot of the community are experiencing it and it's quite interrupting to the usual dev experience.

**Comment by fbenevides** [comment]
@Braden1996 We've just released 1.2.1 and I couldn't reproduce this issue. Could you please update it?

**Comment by jacobmolby** [comment]
@fbenevides I'm on 1.2.1 and I still receive an error on iOS.

It happens nearly every time I switch to another app on the iPhone, while running the react-native project.

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: PusherReactNative:onConnectionStateChange with body: {
    currentState = disconnected;
    previousState = connected;
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter.'
*** First throw call stack:
(0x180abfd0c 0x1982b0ee4 0x182265df0 0x102d5dc40 0x1032343c0 0x103237f04 0x103237f54 0x102b21944 0x102b1d590 0x102b1d840 0x102b2a378 0x102b2c8c0 0x102af77fc 0x1027a8d14 0x1063011a8 0x1062f1fc8 0x1063008ac 0x1063004fc 0x180a7b0c4 0x180a385e8 0x180a4b240 0x1a154d988 0x18324b41c 0x182fe4b88 0x102738044 0x1062603d0)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: PusherReactNative:onConnectionStateChange with body: {
    currentState = disconnected;
    previousState = connected;
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter.'
```

**Comment by Braden1996** [comment]
> @Braden1996 We've just released 1.2.1 and I couldn't reproduce this issue. Could you please update it?

This seems to have resolved the issue for me 🥳

**Comment by benjamin-tang-pusher** [comment]
@jacobmolby we can't reproduce this: is there a particular app you're switching to that causes this, or all apps in general? We have a theory that there is a name conflict with another RN app.

**Comment by Braden1996** [comment]
> @jacobmolby we can't reproduce this: is there a particular app you're switching to that causes this, or all apps in general? We have a theory that there is a name conflict with another RN app.

I've since the same error as @jacobmolby in our Sentry monitoring, but haven't reproduced it personally.

**Comment by tigo0** [comment]
I am getting similar issue, after I reload the app and trying to subscribe right after.

```
libc++abi: terminating with uncaught exception of type NSException
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: PusherReactNative:onConnectionStateChange with body: {
    currentState = connecting;
    previousState = reconnecting;
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter.'
```

**Comment by Pakile** [comment]
I have the same issue, I'm using version 1.2.1
` RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter.'`

**Comment by swaaj** [comment]
Still having the same issue, I'm also using version 1.2.1
````
Your app just crashed. See the error below.
NSInternalInconsistencyException: Error when sending event: PusherReactNative:onConnectionStateChange with body: {
    currentState = disconnected;
    previousState = connected;
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter.
````

**Comment by evrimfeyyaz** [comment]
I'm also experiencing the same issue on version 1.2.1 when I have Flipper on and I receive an event. I use Hermes and I'm on React Native 0.71.3.

**Comment by Braden1996** [comment]
Still happening for me also :(

**Comment by Definence** [comment]
Same issue :(

**Comment by thegregthomp** [comment]
Has this been figured out yet?

**Comment by swaaj** [comment]
It doesn't seem to be figured out. And this is becoming very very annoying for my users complaining about crashes...

**Comment by izakfilmalter** [comment]
Love paying $50 a month for this issue that has been open for half a year.

**Comment by Braden1996** [comment]
Someones else on the team started working with our mobile-app recently.
Gentle reminder to please look into and fix this issue 🙏

![CleanShot 2023-04-18 at 11 25 25](https://user-images.githubusercontent.com/5165963/232749612-437fc9a2-d865-44d6-ad83-2b4e567bf2ee.png)

**Comment by benw-pusher** [comment]
This has been escalated internally for review, i'll update as we get more information.

**Comment by abmirayo** [comment]
Hi everyone, also running into the same issue. My guess, as initially mentioned by people in the team, is that reloads are causing Pusher to init again and again despite already being connected. I want to share a quick patch that is working for me *for now*. I connect to Pusher on a `useEffect` call in my root component. What I do to prevent it from crashing is just to check whether Pusher is connected already or not. So roughly:

```js
  useEffect(() => {
    const connectToPusher = async () => {
      const pusher = Pusher.getInstance();
      try {
        if (pusher.connectionState !== "CONNECTED") {
          await pusher?.init({
            apiKey: "X",
            cluster: "X",
            authEndpoint: `X`,
          });

          await pusher?.connect();
        }
        await pusher?.subscribe({
          channelName: "test",
          onEvent: () => {
            console.log("Test event");
          },
        });
      } catch (e) {
        console.log(`ERROR: ${e}`);
      }
    };

    connectToPusher();
  }, []);

```

The one caveat is that this only works on "soft" reloads, that is, reloads caused by a change in code. Hard reloads will still cause this to crash, since the connection state is lost.  

Just in case this helps while the team works on a fix, since this was driving me crazy as well.

**Comment by Braden1996** [comment]
> This has been escalated internally for review, i'll update as we get more information.

Do you have any updates regarding this? Months are going by with no resolution in-sight. It serious hinders our ability to use Pusher.

**Comment by coolsoftwaretyler** [comment]
We're not seeing this nearly as often after updating to React Native 0.71. Not sure if it's 100% related, but I haven't seen the problem since we updated to Expo 48/RN 0.71. Anyone else notice a change there?

**Comment by SymbiozKenshi** [comment]
I'm using :
```
"@pusher/pusher-websocket-react-native": "^1.2.1"
"expo": "~48.0.18"
"react-native": "0.71.8"
```
and I'm still experiencing crash with this

**Comment by swaaj** [comment]
> I'm using :
> 
> ```
> "@pusher/pusher-websocket-react-native": "^1.2.1"
> "expo": "~48.0.18"
> "react-native": "0.71.8"
> ```
> 
> and I'm still experiencing crash with this

Same here with `@pusher/pusher-websocket-react-native 1.2.2`. 

Could you please do something @fbenevides @benw-pusher?

**Comment by ahmed-khlifi** [comment]
It's almost a year and there is no fix ? and you are charging such high prices for a service that cause app to crash ? please at least do a little effort and reply to us.

**Comment by getnashty** [comment]
Has anyone noticed if this happens the same amount with production builds as it does with development builds? It happens for me pretty much anytime the user comes back to the app after using another app.. how is anyone using this in production?

**Comment by swaaj** [comment]
> Has anyone noticed if this happens the same amount with production builds as it does with development builds? It happens for me pretty much anytime the user comes back to the app after using another app.. how is anyone using this in production?

I am using it in production as a matter of fact. We've had a lot of issues, with end-users complaining. The majority of issues were solved with the last commits. Now crashes have significantly diminished. However, those commits are currently in master branch, but not in 1.2.2 release

@fbenevides @benw-pusher  could you please make a new release?

**Comment by getnashty** [comment]
@swaaj are you using a forked version to include those commits?

**Comment by swaaj** [comment]
Yes I had no other choice :
`    "@pusher/pusher-websocket-react-native": "https://github.com/swaaj/pusher-websocket-react-native.git",
`

**Comment by benjamin-tang-pusher** [comment]
I will nudge the team to create a new release including the last few commits.

**Comment by ahmed-khlifi** [comment]
Is this could be solved this weekend ? we are about to publish a mobile app to production and we need to know if we're going to use pusher or try another solution

**Comment by steelfinger** [comment]
> I will nudge the team to create a new release including the last few commits.

Well, there are only few commits, but the one made only couple of days after the last release (4 moths ago) seems to be a real saviour what comes to crashes with iOS when developing the app. In practice, the app crashes every time a message is received after refresh.

@benjamin-tang-pusher please release?

**Comment by fbenevides** [comment]
@swaaj We just released `1.2.3` version.
