### ISSUE TITLE
Cannot unsubscribe to pusher channel.

### ISSUE THREAD

**Issue by webcyst-gursahb** [pusher/pusher-websocket-react-native#65]
I've used this package in my react-native app but I'm unable to unsubscribe to the pusher channel.
I tried so many things. I searched for it on StackOverflow and other platforms but didn't get anything.

Here is the code of my screen.
```
import { Pusher } from '@pusher/pusher-websocket-react-native';

const pusher = Pusher.getInstance();

useEffect(() => {
     pusher.init({
            apiKey: process.env.API_KEY,
            cluster: process.env.CLUSTER
        });

      pusher.connect();

     pusher.subscribe({
                channelName: process.env.PUSHER_CHANNEL,
                onSubscriptionSucceeded: () => {
                    console.log("Pusher Subscription Added!");
                },
                onSubscriptionError: () => {
                    console.log("Error while Subscribing Channel!");
                },
                onEvent: (data) => {
                    let response = JSON.parse(data.data).results[0];

                    console.log(response);
                }
            });

        return () => {
              pusher.unsubscribe({channelName: process.env.PUSHER_CHANNEL});
              pusher.disconnect();
        }
},[]);
```

When I return to this screen, It will log previous subscriptions to the console. (This code got executed too many times.)

**Comment by tigo0** [comment]
I had similar issue (or maybe the same...), where on iOS it won't subscribe/unsubscribe after the `connect` has been called. Before I tried to `subscribe` to any channel I used to `disconnect`. With  v`1.2.0` it seems fixed for me. More specifically this fix (which fixes yet another issue with the hanging authorizer :))[https://github.com/pusher/pusher-websocket-react-native/pull/68](https://github.com/pusher/pusher-websocket-react-native/pull/68)

**Comment by fbenevides** [comment]
It should be fixed on 1.2.0 @hanzketup @webcyst-gursahb . Could you please update it and check if now it's working? Thanks.

**Comment by tyhour** [comment]
> It should be fixed on 1.2.0 @hanzketup @webcyst-gursahb . Could you please update it and check if now it's working? Thanks.

It was still a problem when I re-subscribed, it was called again and again with the old subscription.

![image](https://user-images.githubusercontent.com/21979709/214487408-4035ab66-cca8-41d7-ba37-3efaf3c7a580.png)

**Comment by leurs247** [comment]
I am facing the same issue with 1.2.1.

**Comment by v64du1** [comment]
Same issue 1.2.2 here also tested with 1.2.0.  Any1 found a fix/workaround so far?

**Comment by Definence** [comment]
Same issue with 1.2.2
