### ISSUE TITLE
Random iOS crash on channel.onEvent and channel.members 

### ISSUE THREAD

**Issue by swaaj** [pusher/pusher-websocket-react-native#93]
# Description

Randomly onEvent or members called on undefined object. That issue is making the app crash on iOS. 
In our code we didn't do anything wrong. It is just completely random.

Example:
![screen](https://user-images.githubusercontent.com/7031126/236260941-0096c4ca-5b64-465d-9de2-1fb33a32d3ef.png)

# Suggestion

Maybe making the calls `channel.onEvent` and `channel.members` conditional with `?.` would solve the issue?

**Comment by Bayramito** [comment]
+1

**Comment by raphaeldcout** [comment]
same problem here

**Comment by fbenevides** [comment]
Can you guys check if it still happens in the latest version?

**Comment by raphaeldcout** [comment]
yes, in the latest version, the problem was fixed with: channel?.onEvent?.(pusherEvent); 

but, I get a new problem iOS crash here:

var member = new PusherMember(_userId, userInfo);
channel.members.set(member.userId, member);
if (_userId === userId) {
  channel.me = member;
}

I'll open a new issue and explain the problem later today

**Comment by swaaj** [comment]
Yes, seems to be fixed for onEvent.

But still the same issue with `channel.members.set(member.userId, member);`
<img width="1128" alt="Capture d’écran 2023-05-26 à 23 17 17" src="https://github.com/pusher/pusher-websocket-react-native/assets/7031126/e50be57c-1fb2-4bde-a2a8-b807283b3373">

**Comment by raphaeldcout** [comment]
> Yes, seems to be fixed for onEvent.
> 
> But still the same issue with `channel.members.set(member.userId, member);` <img alt="Capture d’écran 2023-05-26 à 23 17 17" width="1128" src="https://user-images.githubusercontent.com/7031126/241326909-e50be57c-1fb2-4bde-a2a8-b807283b3373.png">

yes, this same problem happens to me using presence-channel.

It seems to be something related to reconnecting in IOS. For example, leaving the app in the background and opening it again after a while.

**Comment by Kayz-mann** [comment]
I still have the issue: 
WARN  Possible Unhandled Promise Rejection (id: 0):
Error: The package 'pusher-websocket-react-native' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow

Error: The package 'pusher-websocket-react-native' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow

please help out with a solution.

**Comment by swaaj** [comment]
@fbenevides could you please approve and merge this PR ? (#102)[https://github.com/pusher/pusher-websocket-react-native/pull/102]

**Comment by fbenevides** [comment]
We've released [1.3.0](https://github.com/pusher/pusher-websocket-react-native/releases/tag/v1.3.0)
